name: saif_attaya
description: A new Medical Mobile Application.

publish_to: 'none' # flutter pub run build_runner build --delete-conflicting-outputs

version: 1.0.0+1

environment:
  sdk: '>=2.19.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  get_it: ^7.2.0
  injectable: ^1.5.3
  lottie: ^1.4.3
  dartz: ^0.10.1
  flutter_phoenix: ^1.1.0
  freezed: ^2.1.0+1
  freezed_annotation: ^2.1.0
  country_code_picker: ^2.0.2
  equatable: ^2.0.5
  rxdart: ^0.27.3
  firebase_core: ^2.8.0
  firebase_auth: ^4.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  injectable_generator: ^1.5.4
  build_runner: ^2.2.1

  flutter_lints: ^2.0.0

dependency_overrides:
  modal_bottom_sheet: ^3.0.0-pre

flutter:
  uses-material-design: true
  assets:
    # Png
    - assets/images/splash_logo.png
    # Svg
    - assets/images/back_arrow_ar.svg
    - assets/images/back_arrow_en.svg
    # Json
    - assets/json/loading.json
    - assets/json/error.json
    - assets/json/empty.json
    - assets/json/success.json
  fonts:
    - family: NotoNaskhArabic
      fonts:
        - asset: assets/fonts/NotoNaskhArabic-Bold.ttf
          weight: 700
        - asset: assets/fonts/NotoNaskhArabic-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/NotoNaskhArabic-Medium.ttf
          weight: 500
        - asset: assets/fonts/NotoNaskhArabic-Regular.ttf
          weight: 400
        - asset: assets/fonts/NotoNaskhArabic-Light.ttf
          weight: 300